import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [data, setData] = useState([]);

  const fetchData = async () => {
    let data = await fetch("https://jsonplaceholder.typicode.com/posts");
    data = await data.json();
    console.log(data);
    setData(data);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <button
          onClick={() => {
            fetchData();
          }}
        >
          Fetch data
        </button>
        {data.map((dataItem) => {
          return (
            <div key={dataItem.id}>
              <span>{dataItem.id}</span>
              <span>{dataItem.title}</span>
              <span>{dataItem.itemNotFound.somethingElse}</span>
            </div>
          );
        })}
      </main>
    </>
  );
}
